version: '3.4'

services:
  envproviderapp:
    image: envproviderapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
